version: '3'
services:
  nginx:
    image: "nginx:alpine"
    ports:
      # EXPLAIN(tofull) We need to use JAKARNOTATOR_PORT_MAPPED variable
      # because of grafana login redirection
      # if ports set to "8080:80", nginx redirect well localhost:8080 to jakarnotator
      # But nginx will redirect localhost:8080/grafana to grafana with http_port = 80 (port open inside nginx).
      # When we access : http://localhost:8080/grafana in our host browser,
      # grafana will automatically redirect to /login on : http://localhost:80/grafana/login
      # which is not the right port mapped (it should be 8080), 
      # except if we work only with ports "80:80", 
      # or using the same variable like JAKARNOTATOR_PORT_MAPPED (see below in section environnement var in grafana)
      - "${JAKARNOTATOR_PORT_MAPPED}:80"
    depends_on:
      - grafana
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"

  jakarnotator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jakarnotator/bin:/app/bin
      - ./jakarnotator/app.js:/app/app.js
      - ./jakarnotator/node_modules_project:/app/node_modules_project
      - ./jakarnotator/package.json:/app/package.json
      - ./jakarnotator/routes:/app/routes
      - ./jakarnotator/package-lock.json:/app/package-lock.json
      - ./jakarnotator/views:/app/views
      - ./jakarnotator/gulpfile.js:/app/gulpfile.js
      - ./jakarnotator/nodemon.json:/app/nodemon.json
      - ./jakarnotator/public:/app/public
    depends_on:
      - redis
    environment:
      - HOST_REDIS=redis
    # TODO(tofull) Find a way to run browser-sync module via gulp in docker
    # command: npm run dev
    command: npm start

  redis:
    image: "redis"
    logging:
      driver: "none"

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - jakarnotator
    logging:
      driver: "none"

  grafana:
    image: "grafana/grafana:5.1.0"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/provisioning
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:${JAKARNOTATOR_PORT_MAPPED}/grafana
    logging:
      driver: "none"