{
 "title": "jakarnotator_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de requetes entrantes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)",
     "legendFormat": "Nombre de requetes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "content": "<center><img src=\"http://github.com/jakarto3d/media/raw/master/logo_jakarto_fond_lidar.png\" alt=\"logo jakarto\" height=\"300px\"/></center>\n"
  },
  {
   "title": "Temps de réponse par requete sur la dernière minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[1m])"
    }
   ]
  },
  {
   "title": "Nombre d'instance du serveur up",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Log server down",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "up{instance!=\"127.0.0.1:8080\"} != 1"
    }
   ]
  }
 ]
}